# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
setopt auto_cd
plugins=(git npm sudo)
# looks
ZSH_THEME="robbyrussell"

# function to make rm [OPTIONS] -> rm [OPTIONS] -I
function rm { /bin/rm "$@" -I; }

function paccache { apt-cache search "$1" | grep "$1" }

autoload -U colors && colors
setopt correct
export SPROMPT="Correct $fg[red]%R$reset_color to $fg[green]%r?$reset_color (Yes, No, Abort, Edit) "
export TERM='xterm-256color'

# fasd
eval "$(fasd --init auto)"
alias z='nocorrect fasd_cd -d'
unalias s

source $ZSH/oh-my-zsh.sh

# general aliases
alias :q="exit"
alias cls="clear"
alias del="trash-put"
alias dotfiles="cd ~/.dotfiles"
alias gn="screenfetch && sudo pm-hibernate -h now"
alias la="ls -A"
alias ll="ls -lhA"
alias n='nautilus'
alias network-restart="sudo service network-manager restart"
alias pacman="sudo apt-get"
alias refresh="source ~/.zshrc"
alias tmuxconfig="subl ~/.tmux.conf"
alias tree="tree -L 3"
alias vpnbook="sudo openvpn --config /home/sourabh/.vpnbook-euro1-tcp443.ovpn"
alias weechat="weechat-curses"
alias zshconfig="subl ~/.zshrc"

# appcfg.py update .

# PATH
export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:$PATH
export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
export PATH=/usr/games:/home/sourabh/.google_appengine:$PATH
export PATH=/home/sourabh/.node/bin:/opt/sbt/bin:$PATH

# python
alias ipy="ipython"
alias inb="ipython notebook"
alias py="python"
alias pyhttp="python -m SimpleHTTPServer"

# gcc / g++
function gcc { name=$(echo $1 | cut -f1 -d'.'); /usr/bin/gcc "$1" -o "$name.bin" }
function g++ { name=$(echo $1 | cut -f1 -d'.'); /usr/bin/g++ "$1" -o "$name.bin" }
function GCC { name=$(echo $1 | cut -f1 -d'.'); /usr/bin/gcc -Wall -W -Werror "$1" -o "$name.bin" }
function G++ { name=$(echo $1 | cut -f1 -d'.'); /usr/bin/g++ -Wall -W -Werror "$1" -o "$name.bin" }

# tcc
alias tcc="tcc -run -"

# python - django
alias django="python manage.py"

# haskell
alias hs="ghc"
alias ihs="ghci"

# open files
alias o='xdg-open'

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Code
source /usr/local/bin/virtualenvwrapper.sh

# Android SDK path
export PATH=/home/sourabh/.android_sdk/tools:$PATH
export PATH=/home/sourabh/.android_sdk/platform-tools:$PATH
export PATH=/home/sourabh/.android_sdk/build-tools:$PATH

# Android Studio
alias android_studio="/home/sourabh/.android-studio/bin/studio.sh"

# sdcv
alias dict="nocorrect sdcv"

# debian packaging env variables
export DEBEMAIL="sourabh.coder@gmail.com"
export DEBFULLNAME="Sourabh Verma"

# gsutil
export PATH=/home/sourabh/.gsutil:$PATH

# change login background
# sudo -i
# xhost +SI:localuser:lightdm
# su lightdm -s /bin/bash
# gsettings set com.canonical.unity-greeter background 'path-to-image'
# exit

# ??? ag0Q3_6hjQFerbCN2Eewq_esZW2xOQ-xsNqO47m55DA ???
