# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
setopt auto_cd

# looks
ZSH_THEME="robbyrussell"

# function to make rm [OPTIONS] -> rm [OPTIONS] -I
function rm { /bin/rm "$@" -I; }

autoload -U colors && colors
setopt correct
export SPROMPT="Correct $fg[red]%R$reset_color to $fg[green]%r?$reset_color (Yes, No, Abort, Edit) "
export TERM='xterm-256color'

# fasd
eval "$(fasd --init auto)"
alias z='nocorrect fasd_cd -d'

# general aliases
source $ZSH/oh-my-zsh.sh
alias :q="exit"
alias cls="clear"
alias del="trash-put"
alias dotfiles="cd ~/.dotfiles"
alias gn="screenfetch && sudo pm-hibernate -h now"
alias la="ls -A"
alias ll="ls -lhA"
alias n='nautilus'
alias network-restart="sudo service network-manager restart"
alias pacman="sudo apt-get"
alias refresh="source ~/.zshrc"
alias tmuxconfig="subl ~/.tmux.conf"
alias tree="tree -L 3"
alias weechat="weechat-curses"
alias zshconfig="subl ~/.zshrc"

# appcfg.py update .

# PATH
export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/sourabh/.google_appengine:/home/sourabh/.node/bin:/opt/sbt/bin:

# python
alias ipy="ipython"
alias inotebook="ipython notebook"
alias py="python"
alias simpleHttpServer="python -m SimpleHTTPServer"

# gcc
alias GCC="gcc -Wall -W -Werror"
alias G++="g++ -Wall -W -Werror"

# tcc
alias tcc="tcc -run -"

# python - django
alias django="python manage.py"

# haskell
alias hs="ghc"
alias ihs="ghci"

# open files
alias o='xdg-open'

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Code
source /usr/local/bin/virtualenvwrapper.sh

# Android SDK path
export PATH=/home/sourabh/.adt_bundle/sdk/tools:$PATH
export PATH=/home/sourabh/.adt_bundle/sdk/platform-tools:$PATH
alias eclipse="~/.adt_bundle/eclipse/eclipse &"

# sdcv
alias dict="nocorrect sdcv"

# debian packaging env variables
export DEBEMAIL="sourabh.coder@gmail.com"
export DEBFULLNAME="Sourabh Verma"

# gsutil
export PATH=/home/sourabh/.gsutil:$PATH
